name: Rust-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Audit
      run: cargo audit

    - name: Rust Code Coverage
      # You may pin to the exact commit or the version.
      # uses: Swatinem/fucov@304910a1829c88889a0b5671aa5ca7b1abbeebc0
      uses: Swatinem/fucov@v1.0.0
          
